<?php
$title = 'Add new album';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>

<?php

//this provides a default css class and placeholder text for the title element
$album = $form->get('title');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Album title');

//same for the artist element
$artist = $form->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Artist');

//same for the submit button
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');


$form->setAttribute('action', $this->url('album', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>

<div class="form-group">
    <?= $this->formLabel($album) ?>
    <?= $this->formElement($album) ?>
    <?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($artist) ?>
    <?= $this->formElement($artist) ?>
    <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();


































// $form->setAttribute('action', $this->url('album', ['action' => 'add']));
// $form->prepare();

// echo $this->form()->openTag($form);
// echo $this->formHidden($form->get('id'));
// echo $this->formRow($form->get('title'));
// echo $this->formRow($form->get('artist'));
// echo $this->formSubmit($form->get('submit'));
// echo $this->form()->closeTag();

//Alternatively, the process of rendering the form can be simplified by using the bundled formCollection view helper. For example, in the view script above replace all the form-rendering echo statements with:
//echo $this->formCollection($form); //but you still have to wrap formCollection($form) with the open and close form tags