<?php
    $title = 'My albums';
    $this->headTitle($title);
?>
<!--
We always use the escapeHtml() view helper to help protect ourselves from Cross Site Scripting (XSS) vulnerabilities.
-->
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    <a href="<?= $this->url('album', ['action' => 'add']) ?>">Add new album</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th><!--para o campo com os links de edit e delete-->
    </tr>

    <?php foreach ($albums as $album): ?>
        <tr>
            <td><?= $this->escapeHtml($album->title) ?></td>
            <td><?= $this->escapeHtml($album->artist) ?></td>
            <td>
                <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>"Edit</a>
                <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>"Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>

</table>